import { useState } from 'react';
import { movements, type Poet } from '../data/poets';
export default function PoetCatalog({ poets, base }: {poets: Poet[]; base: string}) {
  const [filter, setFilter] = useState('Все поэты');
  const [query, setQuery] = useState('');
  const normalize = (s: string) => s.toLocaleLowerCase('ru').replaceAll('ё','е');
  const filtered = poets.filter(p => (filter === 'Все поэты' || p.movement === filter) && normalize(`${p.first} ${p.last}`).includes(normalize(query.trim())));
  return <><div className="catalog-tools"><div className="filters" aria-label="Направления поэзии">{movements.map(m => <button key={m} className={filter === m ? 'active' : ''} aria-pressed={filter === m} onClick={() => setFilter(m)}>{m}</button>)}</div><label className="search"><span aria-hidden="true">⌕</span><input aria-label="Поиск поэта" placeholder="Найти своего поэта" type="search" value={query} onChange={e => setQuery(e.target.value)}/></label></div><div className="result-line" aria-live="polite">{filtered.length === poets.length ? `Поэтов в коллекции: ${poets.length}` : `Поэтов найдено: ${filtered.length}`}</div><div className="poet-grid">{filtered.map((p) => <a key={p.slug} href={`${base}poets/${p.slug}/`} className={`poet-card ${p.color}`}><div className="poet-art" aria-hidden="true"><span className="art-number">{String(poets.indexOf(p)+1).padStart(2, '0')} / ПОЭТ</span><span className="monogram">{p.mark}</span><span className="art-star">✳</span><span className="art-years">{p.years}</span></div><div className="poet-info"><span className="eyebrow">{p.movement}</span><h3>{p.first}<br/>{p.last}</h3><p>{p.description}</p><span className="card-bottom">{p.poems.length} стихотворения <span>↗</span></span></div></a>)}</div>{filtered.length === 0 && <div className="empty"><h3>Этот голос пока не найден</h3><p>Попробуйте другую фамилию или выберите все направления.</p><button className="button" onClick={() => {setQuery('');setFilter('Все поэты');}}>Сбросить поиск</button></div>}</>;
}
